# Generated by Django 5.0.6 on 2024-06-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='email',
            field=models.TextField(default={'email': 'to1@example.com'}),
        ),
    ]
