# Generated by Django 5.0.6 on 2024-06-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='email',
            field=models.TextField(auto_created=True, default='to1@example.com'),
        ),
    ]
