#!D:\Users\jponte\Documents\codigo-18-backend\semana-2\conectandoflask\entorno_virtual\Scripts\python.exe

import logging
import optparse

import blueprint

parser = optparse.OptionParser('Usage: %prog [-q]')
parser.add_option('-q', '--quiet',
                  dest='quiet',
                  default=False,
                  action='store_true',
                  help='operate quietly')
options, args = parser.parse_args()

if options.quiet:
    logging.root.setLevel(logging.CRITICAL)

for name in blueprint.Blueprint.iter():
    print('  {0}'.format(name))
